/*WAP to  ArithmeticException  divide by 0 to any Number.
 * Mane Manisha .R
 * 4-11-2022
 * 
 */
package Exception;
 class Arithmatic_Exception_div {
       public static void main(String[]args) {
    	   
		 {
			
	try {
           int a1 = 100/2;
           int b = 45*2;
	}
	catch (ArithmeticException e) {
		
		System.out.println((e));
		}
		
 System.out.println("  Process successful : ");

		 
      
		 }}
 }
 
		 
       

       
 
       
 

       



